### ISSUE TITLE
Crash when graph get's resized to zero height

### ISSUE THREAD

**Issue by MFlisar** [patrykandpatrick/vico#200]
I Just placed a graph inside my layout and my layout is collapsible and resizes its content. If I place your graph inside it it crashes (when it gets resized to 0, because it tries to call `coerceIn` with an empty or range).

It's probably a rare use case, but the graph should at least not crash if it gets resized to a zero height...  My suggestion is to use 0 in such a case instead of `coerceIn` which in case of the exception I see below would be the correct y value if the graph is to small to draw anything on the y axis anyway... Or alternatively skip the drawing at all...

**Version:**
compose-m3:1.6.4

**Code**
```
val chartEntryModel = entryModelOf(4f, 12f, 8f, 16f, 20f, 5f, 34f, 72f, 15f, 4f, 12f, 8f, 16f, 20f, 5f, 34f, 72f, 15f)
Chart(
	modifier = Modifier
		.fillMaxWidth()
		.height(100.dp)
		.padding(8.dp),
	chart = lineChart(),
	model = chartEntryModel,
	startAxis = startAxis(),
	bottomAxis = bottomAxis()
)
```

**Stacktrace**
```
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -30.5 is less than minimum 27.5.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1441)
	at com.patrykandpatrick.vico.core.chart.line.LineChart$drawChart$1$1$1.invoke(LineChart.kt:340)
	at com.patrykandpatrick.vico.core.chart.line.LineChart$drawChart$1$1$1.invoke(LineChart.kt:301)
	at com.patrykandpatrick.vico.core.chart.line.LineChart.forEachPointWithinBoundsIndexed(LineChart.kt:469)
	at com.patrykandpatrick.vico.core.chart.line.LineChart.drawChart(LineChart.kt:301)
	at com.patrykandpatrick.vico.core.chart.BaseChart.drawChartInternal(BaseChart.kt:133)
	at com.patrykandpatrick.vico.core.chart.BaseChart.drawScrollableContent(BaseChart.kt:92)
	at com.patrykandpatrick.vico.core.chart.BaseChart.drawScrollableContent(BaseChart.kt:37)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$ChartImpl$6.invoke(Charts.kt:382)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$ChartImpl$6.invoke(Charts.kt:335)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:114)
	...
```

**Comment by patrickmichalik** [comment]
Thanks for the bug report! We’ll look into it.

**Comment by TheRedSpy15** [comment]
Also causing crashes for me. Trying to use AnimatedVisibility() with the composable chart and they don't seem to get along

**Comment by patrickmichalik** [comment]
Vico 1.6.5, which is now rolling out, resolves this issue. Thanks again for the report!
