### ISSUE TITLE
Crash in android 10

### ISSUE THREAD

**Issue by mhrohani1385** [patrykandpatrick/vico#214]
**Describe the bug**
Crash in chart shoing

**Module**

- [ ] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
Going to page that have a chart.
The error may have occurred due to incorrect implementation.

**Expected behaviour**
Showing chart without exception.

**Android versions**
Android 10

**Additional context**

**Comment by patrickmichalik** [comment]
Hello! Thank you for the bug report. Would you be able to provide a stack trace?

**Comment by mhrohani1385** [comment]
java.util.NoSuchElementException
	at com.patrykandpatrick.vico.core.chart.column.ColumnChart.getCellWidth(ColumnChart.kt:319)
	at com.patrykandpatrick.vico.core.chart.column.ColumnChart.getSegmentProperties(ColumnChart.kt:312)
	at com.patrykandpatrick.vico.core.chart.column.ColumnChart.getSegmentProperties(ColumnChart.kt:65)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$ChartImpl$6.invoke(Charts.kt:350)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$ChartImpl$6.invoke(Charts.kt:335)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:104)
	at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:381)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:371)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:397)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:124)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:396)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1010)
	at android.view.View.draw(View.java:22080)
	at android.view.View.updateDisplayListIfDirty(View.java:20946)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4450)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
	at android.view.View.updateDisplayListIfDirty(View.java:20904)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4450)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
	at android.view.View.updateDisplayListIfDirty(View.java:20904)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4450)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
	at android.view.View.updateDisplayListIfDirty(View.java:20904)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4450)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4423)
	at android.view.View.updateDisplayListIfDirty(View.java:20904)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:673)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3910)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3616)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2890)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1827)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8015)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1062)
	at android.view.Choreographer.doCallbacks(Choreographer.java:884)
	at android.view.Choreographer.doFrame(Choreographer.java:814)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1047)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by patrickmichalik** [comment]
This seems to suggest that [`ColumnChart#columns`](https://patrykandpatrick.com/vico/api/vico/core/com.patrykandpatrick.vico.core.chart.column/-column-chart/columns) is empty, which it shouldn’t be. Please ensure that the collection has at least one element.

**Comment by mhrohani1385** [comment]
I think you say right.
I will edit code and would probably close the issue if it worked.
Thank you!

**Comment by patrickmichalik** [comment]
You’re welcome! I’m glad the problem is resolved.
