### ISSUE TITLE
java.util.ConcurrentModificationException when using `ComposedChartView`

### ISSUE THREAD

**Issue by KesWalker** [patrykandpatrick/vico#239]
**Describe the bug**
When using `ComposedChartView` with `ComposedChartEntryModelProducer` the app will sometimes crash after about 3 seconds.

**Module**

- [ ] `compose`
- [x] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

This is what my code looks like:

        (binding.weatherChart.chart as ComposedChart).charts.let {
            (it.first() as ColumnChart).targetVerticalAxisPosition = AxisPosition.Vertical.End
            (it.last() as LineChart).targetVerticalAxisPosition = AxisPosition.Vertical.Start
        }
        (binding.weatherChart.startAxis as Axis).guideline = null
        (binding.weatherChart.bottomAxis as Axis).guideline = null

        (binding.weatherChart.startAxis as VerticalAxis).valueFormatter =
            AxisValueFormatter { value, _ -> value.toInt().toString() }

        binding.weatherChart.entryProducer = chartValues

The error that occurs:

        java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:792)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
        at com.patrykandpatryk.vico.core.chart.values.ChartValuesManager.tryUpdate(ChartValuesManager.kt:113)
        at com.patrykandpatryk.vico.core.chart.values.ChartValuesManager.tryUpdate$default(ChartValuesManager.kt:61)
        at com.patrykandpatryk.vico.core.chart.values.ChartValuesManager.tryUpdate(ChartValuesManager.kt:79)
        at com.patrykandpatryk.vico.core.chart.column.ColumnChart.updateChartValues(ColumnChart.kt:298)
        at com.patrykandpatryk.vico.core.chart.column.ColumnChart.updateChartValues(ColumnChart.kt:65)
        at com.patrykandpatryk.vico.core.chart.composed.ComposedChart.updateChartValues(ComposedChart.kt:132)
        at com.patrykandpatryk.vico.core.chart.composed.ComposedChart.updateChartValues(ComposedChart.kt:42)
        at com.patrykandpatryk.vico.view.chart.BaseChartView.tryInvalidate(BaseChartView.kt:304)
        at com.patrykandpatryk.vico.view.chart.BaseChartView.setModel(BaseChartView.kt:289)
        at com.patrykandpatryk.vico.view.chart.BaseChartView$registerForUpdates$3.invoke(BaseChartView.kt:227)
        at com.patrykandpatryk.vico.view.chart.BaseChartView$registerForUpdates$3.invoke(BaseChartView.kt:216)
        at com.patrykandpatryk.vico.core.entry.composed.ComposedChartEntryModelProducer$CompositeModelReceiver.onModelUpdate$lambda$1(ComposedChartEntryModelProducer.kt:104)
        at com.patrykandpatryk.vico.core.entry.composed.ComposedChartEntryModelProducer$CompositeModelReceiver.$r8$lambda$bkYwW_15Gu0xsrpHmiIgGzUI0ak(Unknown Source:0)
        at com.patrykandpatryk.vico.core.entry.composed.ComposedChartEntryModelProducer$CompositeModelReceiver$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

The chart will display fine and everything works for about 3 seconds until it crashes.

**Comment by KesWalker** [comment]
Seems to be fixed by setting the model like:

        binding.weatherChart.setModel(chartValues.getModel())

Rather than:

    binding.weatherChart.entryProducer = chartValues

**Comment by Gowsky** [comment]
Hello @KesWalker,
`binding.weatherChart.setModel(chartValues.getModel())` and `binding.weatherChart.entryProducer = chartValues` will give you a complete different behavior.
Can you provide a minimal MRE?

**Comment by Gowsky** [comment]
We were able to reproduce and fix the crash.

**Comment by patrickmichalik** [comment]
Hello! Vico 1.6.6 resolves this issue. Thanks for the feedback!
