### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot round NaN value.

### ISSUE THREAD

**Issue by mildroid** [patrykandpatrick/vico#319]
**Describe the bug**
I am getting a `java.lang.IllegalArgumentException: Cannot round NaN value` error when I add **bottomAxis** to a one particular chart composable. However, with other cases, there are no problems with **bottomAxis**.

**Module**

-  `compose`
-  `compose-m3`

**To reproduce**
The error thrown chart:
```
Chart(
            modifier = modifier,
            chart = columnChart(
                axisValuesOverrider = AxisValuesOverrider
                    .fixed(maxY = (oldChartStepHandler(maxHour) * MILLIS_PER_HOUR).toFloat()),
                persistentMarkers = mapOf((selectedInfo.selectedDay - 1).toFloat() to marker()),
                columns = listOf(MaterialTheme.colorScheme.primary).map { ... },
                spacing = MaterialTheme.spacing.small,
            ),
            startAxis = startAxis(
                maxLabelCount = 4,
                valueFormatter = HourAxisValueFormatter(),
                guideline = axisGuidelineComponent(MaterialTheme.colorScheme.primary.copy(alpha = 0.08f))
            ),
            chartModelProducer = chartEntryModelProducer,
            bottomAxis = bottomAxis(
                valueFormatter = DayAxisValueFormatter(),
                label = axisLabelComponent(typeface = LocalContext.current.typeface()),
                guideline = null,
            )/*The exception will throw with or without these parameters */,
            marker = marker(),
            markerVisibilityChangeListener = object :
                MarkerVisibilityChangeListener {
                override fun onMarkerShown(
                    marker: Marker,
                    markerEntryModels: List<Marker.EntryModel>
                ) {
                    super.onMarkerShown(marker, markerEntryModels)
                    markerEntryModels.forEach {
                        onSelectDay(it.entry.x.toInt() + 1)
                    }
                }
            },
        )
```

**ERROR**
```
FATAL EXCEPTION: main
Process: com.mildroid.cleanmaster, PID: 10394
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
	at com.patrykandpatryk.vico.core.axis.horizontal.DefaultHorizontalAxisItemPlacer.getLabelValues(DefaultHorizontalAxisItemPlacer.kt:120)
	at com.patrykandpatryk.vico.core.axis.horizontal.HorizontalAxis.drawBehindChart(HorizontalAxis.kt:107)
	at com.patrykandpatryk.vico.core.axis.AxisManager.drawBehindChart(AxisManager.kt:207)
	at com.patrykandpatryk.vico.compose.chart.ChartsKt$ChartImpl$5.invoke(Charts.kt:408)
	at com.patrykandpatryk.vico.compose.chart.ChartsKt$ChartImpl$5.invoke(Charts.kt:357)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:114)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:370)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:395)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:395)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:301)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1046)
	at android.view.View.draw(View.java:21424)
	at android.view.View.updateDisplayListIfDirty(View.java:20298)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
	at android.view.View.updateDisplayListIfDirty(View.java:20258)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
	at android.view.View.updateDisplayListIfDirty(View.java:20258)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
	at android.view.View.updateDisplayListIfDirty(View.java:20258)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4372)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4345)
	at android.view.View.updateDisplayListIfDirty(View.java:20258)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

Thank you.

**Comment by patrickmichalik** [comment]
Hello! Thank you for the bug report. Unfortunately, because the example isn’t self-contained, we’re unable to reproduce the issue. Unresolved references include `oldChartStepHandler`, `maxHour`, and `HourAxisValueFormatter`. Please see [here](https://vercel.com/guides/creating-a-minimal-reproducible-example) for information on the boxes that should be checked by a minimal reproducible example.

**Comment by mildroid** [comment]
I have tested the references you mentioned, and I can confirm that they are not the reason this exception throws.
I have also tested the case myself, and I have found that the cause of the issue is `spacing = MaterialTheme.spacing.small /*Or any other dp value*/` of columnChart.

this is  minimal reproducible example that demonstrates the issue.
```
Chart(
        modifier = modifier,
        chart = columnChart(
            spacing = MaterialTheme.spacing.small,/* Or any other dp value*/
        ),
        chartModelProducer = chartEntryModelProducer,
        bottomAxis = bottomAxis(),
    )
```


I hope this helps!

**Comment by patrickmichalik** [comment]
Thank you! Could you also share some information on the data set? It doesn’t look like the issue occurs for all data sets—the following, for example, appears to work as expected.

```kt
val chartEntryModelProducer = ChartEntryModelProducer(entriesOf(2f, 4f, 8f, 12f))

@Preview
@Composable
fun Example() {
    Chart(
        chart = columnChart(spacing = 8.dp),
        chartModelProducer = chartEntryModelProducer,
        bottomAxis = bottomAxis(),
    )
}
```

**Comment by mildroid** [comment]
My data set is dynamic.
Its look like the exception throws when passing `ChartEntryModelProducer` to chart **without** any entry.

**Comment by patrickmichalik** [comment]
Ah, indeed. I tested this previously, but not with `spacing` set to 8 dp. We’ll investigate and release a hotfix as soon as possible.

**Comment by patrickmichalik** [comment]
We’ve identified and resolved the issue, but Maven Central is giving us a hard time. While we hope to release the hotfix today, I’ve not been able to get much to work over the past four hours. It’s timeout after timeout. Sorry for the wait.

**Comment by mildroid** [comment]
Thank you for all the effort.

**Comment by patrickmichalik** [comment]
[Vico 1.7.3](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.3), which resolves this issue, is now rolling out. Thanks for the report!
