### ISSUE TITLE
Crash on Android 14 with Compose 1.6.0-alpha03

### ISSUE THREAD

**Issue by savvasdalkitsis** [patrykandpatrick/vico#366]
**Describe the bug**
I am getting the following crash on Android 14 on the latest alpha of Compose:

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
	at com.patrykandpatrick.vico.compose.chart.ChartsKt.ChartImpl(Charts.kt:326)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$1.invoke(Charts.kt:137)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$1.invoke(Charts.kt:135)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2507)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2776)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3255)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3206)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:864)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1125)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:580)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:548)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:878)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@304f0f8, androidx.compose.ui.platform.MotionDurationScaleImpl@25659d1, StandaloneCoroutine{Cancelling}@6c81c36, AndroidUiDispatcher@390a737]
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[zip file "/data/app/~~WHTzZK4i53Ir5mkn_NN5bQ==/com.savvasdalkitsis.uhuruphotos.debug-I0Yk4hU-12x-FsMzfRGQAA==/base.apk"],nativeLibraryDirectories=[/data/app/~~WHTzZK4i53Ir5mkn_NN5bQ==/com.savvasdalkitsis.uhuruphotos.debug-I0Yk4hU-12x-FsMzfRGQAA==/lib/x86_64, /data/app/~~WHTzZK4i53Ir5mkn_NN5bQ==/com.savvasdalkitsis.uhuruphotos.debug-I0Yk4hU-12x-FsMzfRGQAA==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 33 more

**Module**

- [ ] `compose`
- [ ] `views`
- [x] `compose-m2`
- [ ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**Android versions**
14

**Comment by patrickmichalik** [comment]
Hello! This suggests that the version of Jetpack Compose used by Vico and the version used by your project are incompatible. Vico uses stable Compose versions, and version 1.10.1 of the library depends on the latest release of the Compose BOM, 2023.08.00. Whether Vico works with a newer Compose version than the one it depends on comes down to how the two Compose versions differ. I’m afraid we have no power here. Once Compose 1.6.0 is stable and there’s a BOM release that includes it, we’ll update the BOM in Vico.

**Comment by EzekielWachira** [comment]
I'm using  `compose-bom = "2023.08.00"` and still crashes

**Comment by patrickmichalik** [comment]
Could you provide a minimal reproducible example, @EzekielWachira? Unfortunately, with no information on your setup, we’re unable to help. We don’t believe Vico is at fault. Please see these posts: [1](https://issuetracker.google.com/issues/297890485), [2](https://stackoverflow.com/questions/76950205/failed-resolution-of-landroidx-compose-runtime-primitivesnapshotstatekt), [3](https://github.com/google/accompanist/issues/1701).
