### ISSUE TITLE
Exception: java.lang.IllegalArgumentException: Cannot round NaN value

### ISSUE THREAD

**Issue by subhashisbhowmik** [patrykandpatrick/vico#374]
**Describe the bug**
I'm trying to draw a dynamic chart:
```

@Preview
@Composable
fun ChartPreview() {
    fun getEntries() = mutableListOf(FloatEntry(x=1747.2343F, y=9203.319F), FloatEntry(x=1747.238F, y=8646.208F), FloatEntry(x=1747.2417F, y=8922.347F), FloatEntry(x=1747.2456F, y=8952.614F), FloatEntry(x=1747.2493F, y=8630.625F), FloatEntry(x=1747.253F, y=9147.827F), FloatEntry(x=1747.2568F, y=8855.011F), FloatEntry(x=1747.2605F, y=8721.359F), FloatEntry(x=1747.2643F, y=9198.294F), FloatEntry(x=1747.2681F, y=9282.166F), FloatEntry(x=1747.2719F, y=9255.02F), FloatEntry(x=1747.2755F, y=8477.763F), FloatEntry(x=1747.2792F, y=8143.821F), FloatEntry(x=1747.2831F, y=9072.632F), FloatEntry(x=1747.2867F, y=9249.497F), FloatEntry(x=1747.2905F, y=8836.102F), FloatEntry(x=1747.2943F, y=8698.147F), FloatEntry(x=1747.2981F, y=9273.426F), FloatEntry(x=1747.3018F, y=9278.309F), FloatEntry(x=1747.3054F, y=8761.996F), FloatEntry(x=1747.3093F, y=8704.141F), FloatEntry(x=1747.3206F, y=9326.415F), FloatEntry(x=1747.3243F, y=9273.834F), FloatEntry(x=1747.328F, y=9273.009F), FloatEntry(x=1747.3318F, y=9280.718F), FloatEntry(x=1747.3356F, y=8726.299F), FloatEntry(x=1747.3392F, y=8082.33F), FloatEntry(x=1747.343F, y=8396.612F), FloatEntry(x=1747.3468F, y=8595.598F), FloatEntry(x=1747.3506F, y=8569.604F), FloatEntry(x=1747.3542F, y=8898.904F), FloatEntry(x=1747.358F, y=9310.803F))
    val chartModelProducer = ChartEntryModelProducer(getEntries())
    Chart(
        chart = lineChart(),
        chartModelProducer = chartModelProducer,
        startAxis = rememberStartAxis(),
        bottomAxis = rememberBottomAxis(),
    )
}
```
(Note that the values would be dynamic, but I took a subset of a snapshot of the real data)
Getting the following exception:

```
java.lang.IllegalArgumentException: Cannot round NaN value.
                                         	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
                                         	at com.patrykandpatrick.vico.core.axis.horizontal.DefaultHorizontalAxisItemPlacer.getLabelValues(DefaultHorizontalAxisItemPlacer.kt:129)
                                         	at com.patrykandpatrick.vico.core.axis.horizontal.HorizontalAxis.drawBehindChart(HorizontalAxis.kt:109)
                                         	at com.patrykandpatrick.vico.core.axis.AxisManager.drawBehindChart(AxisManager.kt:207)
                                         	at com.patrykandpatrick.vico.compose.chart.ChartsKt$ChartImpl$5.invoke(Charts.kt:400)
                                         	at com.patrykandpatrick.vico.compose.chart.ChartsKt$ChartImpl$5.invoke(Charts.kt:350)
                                         	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:114)
                                         	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:370)
                                         	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
                                         	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
                                         	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
                                         	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
                                         	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
                                         	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
                                         	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
                                         	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
                                         	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
                                         	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
                                         	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
                                         	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
                                         	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
                                         	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)
                                         	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
                                         	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
                                         	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
                                         	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
                                         	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:395)
                                         	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
                                         	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
                                         	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
                                         	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                         	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                         	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                         	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
                                         	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:395)
                                         	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
23:40:16.005 AndroidRuntime           E  	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
                                         	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:301)
                                         	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1046)
                                         	at android.view.View.draw(View.java:24409)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23267)
                                         	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
                                         	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23214)
                                         	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
                                         	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23214)
                                         	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
                                         	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23214)
                                         	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
                                         	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23214)
                                         	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
                                         	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23214)
                                         	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
                                         	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
                                         	at android.view.View.updateDisplayListIfDirty(View.java:23214)
                                         	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)
                                         	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)
                                         	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)
                                         	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)
                                         	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
                                         	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
                                         	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
                                         	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
                                         	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
                                         	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
                                         	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
                                         	at android.view.Choreographer.doFrame(Choreographer.java:852)
                                         	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
                                         	at android.os.Handler.handleCallback(Handler.java:942)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at android.os.Looper.loopOnce(Looper.java:226)
                                         	at android.os.Looper.loop(Looper.java:313)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
Use the preview or call the composable.

**Expected behavior**
No errors are expected

**Android versions**
13

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. It looks like the precision of your _x_ values is too large. For `Float`s, four decimal places are the limit. However, if the input data has the maximum precision, as is the case here, no room is left for Vico to run calculations that require greater precision than that of the input data. Here, the GCD algorithm is failing. If you were to specify the _x_ step manually and make it sufficiently large—say, 0.01—no crash would occur. Still, due to the precision of the _x_ values, not everything would behave as expected. From what we can tell, two decimal places are the limit. If you require greater precision, you’ll have to normalize your _x_ values by multiplying them by such a power of 10 that they have no more than two decimal places. In your case, that’d be 100, but the safest solution would be to use a multiplier of 10,000. To ensure that accurate labels are displayed along the chart’s horizontal axis, you can create a custom `AxisValueFormatter` and divide the _x_ values by the aforementioned power of 10 therein. We’ll look into adding a check that throws a descriptive exception when this issue occurs.

By the way, I’ve noticed that, in the example provided, a `ChartEntryModelProducer` instance is created in a composable function. I imagine that you may have done this only for the purpose of the example, but if not, please keep in mind that this can significantly degrade performance. We recommend either using `remember` or, preferably, instantiating `ChartEntryModelProducer` only in `ViewModel` classes.

**Comment by subhashisbhowmik** [comment]
@patrickmichalik  I see, that works! Can you please explain the use of the GCD and the meaning of steps?

For your second question, yes it is just for the sake of this post.

**Comment by patrickmichalik** [comment]
The GCD (greatest common divisor) of the differences between a chart’s _x_ values is used as its default _x_ step. We typically define the _x_ step as “the difference between neighboring major entries’ _x_ values.” This value affects how the chart is scaled. For example, `LineChart#spacing` is the distance between major entries. Also, by default, `HorizontalAxis` instances draw a label for each major entry. By locking in a chart’s _x_ step, you can add intermediate entries without having to worry about rescaling the chart, changing the setup of its `HorizontalAxis` instances, etc. Let’s say you have the following `ChartEntryModel`.

```kt
val chartEntryModel = entryModelOf(
    0 to 1,
    1 to 5,
    2 to 3,
    3 to 6,
    4 to 1,
    5 to 7,
    6 to 8,
    7 to 2,
    8 to 8,
    9 to 1,
    10 to 3,
    11 to 4,
    12 to 5,
)
```

A simple line chart with this `ChartEntryModel` looks like this:

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/b7b1630e-c056-4be4-8c32-0bd73af0305d" width="360" />

Vico has set the _x_ step to 1. Let’s now add an entry with an _x_ value of 2.5.

```kt
val chartEntryModel = entryModelOf(
    0 to 1,
    1 to 5,
    2 to 3,
    2.5 to 1,
    3 to 6,
    4 to 1,
    5 to 7,
    6 to 8,
    7 to 2,
    8 to 8,
    9 to 1,
    10 to 3,
    11 to 4,
    12 to 5,
)
```

We get the following.

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/9debfbee-9790-4968-b413-0c67dc7cf32b" width="360" />

The _x_ step is now 0.5. Let’s override the _x_ step and make it 1 again. Here’s the result:

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/864a8c72-8005-41a9-a6c4-10f879159867" width="360" />

I hope this clears things up.

**Comment by patrickmichalik** [comment]
As of [Vico 1.13.0 Alpha 3](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.3), when the precision of a chart’s x values is too large for the GCD of their deltas to be calculated, a descriptive exception is thrown. We’ll close this issue once Vico 1.13.0 is stable. Cheers!

**Comment by patrickmichalik** [comment]
I’ll be removing the “bug” label because we now use discussions for everything but bug reports, making the “bug” label redundant. Please rest assured that this doesn’t change anything about the bug report.

**Comment by subhashisbhowmik** [comment]
@patrickmichalik In the 1.13.0 alpha 5, it seems to ignore the `getXStep` param passed.

```
    @Composable
    fun VicoChart(producer: ChartEntryModelProducer) {
        Chart(
            chart = lineChart(),
            chartModelProducer = producer,
            startAxis = rememberStartAxis(),
            bottomAxis = rememberBottomAxis(),
            diffAnimationSpec = null
        ) { 1F }
    }
```
I'm also passing the params like `t.round2F()` where
```
        fun Float.round2F(): Float {
            return (this * 100).roundToLong().toFloat() / 100F
        }
```
I'm still getting this:
```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.artemis.sync, PID: 3945
java.lang.IllegalArgumentException: The precision of the x values is too large. The maximum precision is two decimal places.
	at com.patrykandpatrick.vico.core.entry.ChartEntryExtensionsKt.calculateXGcd(ChartEntryExtensions.kt:108)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel(ChartEntryModelProducer.kt:147)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel$default(ChartEntryModelProducer.kt:133)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getModel(ChartEntryModelProducer.kt:153)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer$UpdateReceiver.handleUpdate(ChartEntryModelProducer.kt:208)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer$setEntriesSuspending$3$1.invokeSuspend(ChartEntryModelProducer.kt:104)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c26edd1, Dispatchers.Default]
Sending signal. PID: 3945 SIG: 9
```

Can you please take a look? @patrickmichalik

**Comment by patrickmichalik** [comment]
`getXStep` doesn’t prevent `calculateXGcd` from being run, @subhashisbhowmik, so an exception in `calculateXGcd` doesn’t point to `getXStep` being ignored. In other words, if `calculateXGcd` weren’t failing, the chart would be created, and it would have the requested _x_ step of 1.

It’s thus sufficient to determine what’s causing the exception. Based on the information provided, I suspect that there may be an issue wherein the data set includes the same _x_ value several times and no other _x_ values. Let’s say you have two _x_ values, 0.015 and 0.016. The rounding function will turn both into 0.02. `calculateXGcd` will determine the GCD of the _x_ deltas to be zero, and it’ll throw an exception. Please confirm that there’s no such duplication. If there isn’t, could you please share the data set for which the crash occurs?

**Comment by subhashisbhowmik** [comment]
I see, that might be the case here. So what is the correct approach here for say if two x values are 1.001 and 1.004?

**Comment by patrickmichalik** [comment]
You can use a multiplier and an `AxisValueFormatter`. Take a look:

```kt
const val X_MULTIPLIER = 10
val data = listOf(1.001 to 1, 1.004 to 2)
val chartEntryModelProducer = ChartEntryModelProducer(data.map { (x, y) -> entryOf(X_MULTIPLIER * x, y) })
val bottomAxisValueFormatter = AxisValueFormatter<AxisPosition.Horizontal.Bottom> { x, _ -> "${x / X_MULTIPLIER}" }

@Composable
@Preview(showBackground = true, backgroundColor = 0xffffffff)
fun Example() {
    Chart(
        chart = lineChart(),
        chartModelProducer = chartEntryModelProducer,
        startAxis = rememberStartAxis(),
        bottomAxis = rememberBottomAxis(valueFormatter = bottomAxisValueFormatter),
    )
}
```

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/051895db-ef93-43c0-a9b7-e694fdafca6d" width="720" />

The multiplier should be such a power of ten that the _x_ values’ precision doesn’t exceed the threshold, which is in place because the `Float` data type has limited precision. Here, because 1.001 and 1.004 exceed the limit by one decimal place, ten to the power of one is sufficient.

**Comment by patrickmichalik** [comment]
[Vico 1.13.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0) is now out, so I’ll be closing this issue. Thanks!
