### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;

### ISSUE THREAD

**Issue by ahmed2146** [patrykandpatrick/vico#375]
**Describe the bug**

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [x] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
I'm using your new version Apis
    implementation 'com.patrykandpatrick.vico:compose-m3:1.11.1'
    implementation 'com.patrykandpatrick.vico:compose:1.11.1'
    implementation 'com.patrykandpatrick.vico:core:1.11.1'
it's crashing on making view run time 
same code is working fine on 
implementation 'com.patrykandpatrick.vico:compose-m3:1.9.2'
    implementation 'com.patrykandpatrick.vico:core:1.9.2'

**Expected behavior**
Application is Crashing 
FATAL EXCEPTION: main
                                                    Process: work.space.cleanarchitecture, PID: 30879
                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
                                                    	at com.patrykandpatrick.vico.compose.chart.ChartsKt.ChartImpl(Charts.kt:327)
                                                    	at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$1.invoke(Charts.kt:138)
                                                    	at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$1.invoke(Charts.kt:136)
                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2522)
                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2791)
                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3270)
                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3221)
                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:932)
                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1143)
                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:580)
                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:548)
                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
                                                    	at android.view.Choreographer.doFrame(Choreographer.java:792)
                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                    	at android.os.Looper.loop(Looper.java:313)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@bceb415, androidx.compose.ui.platform.MotionDurationScaleImpl@f1f432a, StandaloneCoroutine{Cancelling}@342951b, AndroidUiDispatcher@aa9e6b8]
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[dex file "/data/data/work.space.cleanarchitecture/code_cache/.overlay/base.apk/classes10.dex", dex file "/data/data/work.space.cleanarchitecture/code_cache/.overlay/base.apk/classes6.dex", zip file "/data/app/~~iRjBWMUpW3hrRO41qVAzUQ==/work.space.cleanarchitecture-1CFrqMUGpcysJp3CAV3_WA==/base.apk"],nativeLibraryDirectories=[/data/app/~~iRjBWMUpW3hrRO41qVAzUQ==/work.space.cleanarchitecture-1CFrqMUGpcysJp3CAV3_WA==/lib/arm, /system/lib, /system/system_ext/lib]]
                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                    	... 32 more

**Android versions**
 compose_version = '1.5.2'
 compileSdk 34
 minSdk 23

**Comment by ahmed2146** [comment]
thanks

**Comment by patrickmichalik** [comment]
You’re welcome!
