### ISSUE TITLE
WearOS NoClassDefFoundError / ClassNotFoundException

### ISSUE THREAD

**Issue by Ynnck123** [patrykandpatrick/vico#451]
### How to reproduce

When trying to use the library in my WearOS app: 
```
implementation("com.patrykandpatrick.vico:compose:1.13.0-alpha9")
```

creating a `Chart` composable in the following way as en example:

```
Chart(
      modifier = Modifier.size(200.dp),
      model = entryModelOf(1 to 100),
      chart = lineChart(),
)
```

### Observed behavior

The following error gets thrown:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
    at com.patrykandpatrick.vico.compose.chart.scroll.ChartScrollState.<init>(ChartScrollState.kt:37)
    at com.patrykandpatrick.vico.compose.chart.scroll.ChartScrollStateKt.rememberChartScrollState(ChartScrollState.kt:116)
    at com.patrykandpatrick.vico.compose.chart.ChartsKt.Chart(Charts.kt:221)
                                                                                                    	
 ..
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[dex file "/data/data/com.myapp/code_cache/.overlay/base.apk/classes15.dex", zip file "/data/app/~~xNxtcnefZnleevvro9uEZA==/com.myapp-R0O0ew-6RlcrckUjsu7kHw==/base.apk"],nativeLibraryDirectories=[/data/app/~~xNxtcnefZnleevvro9uEZA==/com.myapp-R0O0ew-6RlcrckUjsu7kHw==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 31 more                                                           	
```

When I switch to the latest stable version `1.12.0` the type of exception is the same, but the stacktrace slightly changes to a different line of the cause:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
	at com.patrykandpatrick.vico.compose.chart.ChartsKt.ChartImpl(Charts.kt:327)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$5.invoke(Charts.kt:281)
	at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$5.invoke(Charts.kt:280)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
```

### Expected behavior

The code gets rendered as expected.

### Vico version(s)

Latest stable version, Latest unstable version

### Android version(s)

WearOS API 30

**Comment by patrickmichalik** [comment]
Hello! This is a result of a Jetpack Compose version mismatch. For Vico 1.13.0 Alpha 9, please ensure you’re using version 2023.10.01 of the Compose BOM. For Vico 1.12.0, please use version 2023.09.00. Note that some libraries appear to override the Compose version, so it’s important to update them too. One such library is `androidx.compose.material:material-icons-core`. If you have trouble resolving the problem, please share the relevant Gradle files, and we’ll take a look.
