### ISSUE TITLE
StackOverflowError when calling ChartEntryModelProducer::setEntries()

### ISSUE THREAD

**Issue by littleant** [patrykandpatrick/vico#502]
### How to reproduce

I called `chartEntryModelProducer.setEntries()` in my `ViewModel` and got a `StackOverflowError`.
There are only 76 entries in the list and I don't think the entry-count is the problem.

It works fine most of the time.

I'm calling `setEntries()` in `someflow.mapLatest {}`. Maybe it's some kind of sync problem between co-routines?

### Observed behavior

Got this Exception:

```
FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                    Process: redacted, PID: 16197
                                                                                                    java.lang.StackOverflowError: stack size 1039KB
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:40)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:38)
--- repeated many, many times ---
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:38)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:40)
2023-12-21 14:55:38.619 16197-16226 AndroidRuntime          redacted		               E  	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:38)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:40)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:38)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:40)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:40)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWithImpl(NumberExtensions.kt:38)
                                                                                                    	at com.patrykandpatryk.vico.core.extension.NumberExtensionsKt.gcdWith(NumberExtensions.kt:43)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryExtensionsKt.calculateXGcd(ChartEntryExtensions.kt:93)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.getInternalModel(ChartEntryModelProducer.kt:151)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.getInternalModel$default(ChartEntryModelProducer.kt:133)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.getModel(ChartEntryModelProducer.kt:158)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer$UpdateReceiver.handleUpdate(ChartEntryModelProducer.kt:213)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.registerForUpdates(ChartEntryModelProducer.kt:190)
                                                                                                    	at com.patrykandpatryk.vico.compose.chart.entry.ChartEntryModelExtensionsKt$collectAsState$1$1.invokeSuspend(ChartEntryModelExtensions.kt:116)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@9ee80f6, androidx.compose.runtime.BroadcastFrameClock@a1c0cf7, StandaloneCoroutine{Cancelling}@7eef764, Dispatchers.Default]
```

### Expected behavior

No crash, with new values in the chart.

### Vico version(s)

Latest stable version

### Android version(s)

14

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. The chart data is relevant here. Could you please share a set of _x_ and _y_ values for which the crash occurs? You could, for example, update your code to send a log message containing the _x_ and _y_ values before `setEntries` is invoked.

**Comment by littleant** [comment]
I struggle to reproduce it right now. I'll post the entries once, I get the `StackOverflowError` again.
Instead I get this error, even though there are no duplicate values:
```
FATAL EXCEPTION: DefaultDispatcher-worker-1
                                                                                                    Process: redacted, PID: 20412
                                                                                                    java.lang.IllegalArgumentException: The precision of the x values is too large. The maximum is two decimal places.
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryExtensionsKt.calculateXGcd(ChartEntryExtensions.kt:94)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.getInternalModel(ChartEntryModelProducer.kt:151)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.getInternalModel$default(ChartEntryModelProducer.kt:133)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.getModel(ChartEntryModelProducer.kt:158)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer$UpdateReceiver.handleUpdate(ChartEntryModelProducer.kt:213)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.registerForUpdates(ChartEntryModelProducer.kt:190)
                                                                                                    	at com.patrykandpatryk.vico.compose.chart.entry.ChartEntryModelExtensionsKt$collectAsState$1$1.invokeSuspend(ChartEntryModelExtensions.kt:116)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e1a8da, androidx.compose.runtime.BroadcastFrameClock@423810b, StandaloneCoroutine{Cancelling}@df17be8, Dispatchers.Default]
```

Here are the values I put in `setEntries()`:
[precision-too-large-exception.txt](https://github.com/patrykandpatrick/vico/files/13745502/precision-too-large-exception.txt)

I suspect a concurrency problem, but don't know how to debug it further.

**Comment by littleant** [comment]
I wrote a test-case with the `FloatEntries` from my last comment. (I copied the internal implementation from Vico files, so I could test them):
[ChartEntryExtensionsTest.kt.txt](https://github.com/patrykandpatrick/vico/files/13750859/ChartEntryExtensionsTest.kt.txt)

There seems to be a bug in `calculateXGcd()`: The last `FloatEntry` causes the exception to incorrectly being thrown. If you comment it out, no exception is thrown. The x-value of that entry is unique up to the first three digits (864xx.x) which should be enough?

Sorry for mixing two different exceptions in one issue, hope it's ok.

**Comment by patrickmichalik** [comment]
Thanks for looking into this, @littleant! It’s not necessarily a deal-breaker that the first proposed solution causes the last test to fail. The GCD algorithm is in place not to detect excessive precision, but rather to determine the default _x_ step. The zero check is present because an _x_ step of zero would cause unexpected behavior. It happens to be the case that `calculateXGcd` produces such an _x_ step for overly precise _x_ values. Such _x_ values can cause other issues too, and there already are instances in which they go undetected—perhaps a dedicated precision check should be added.

The `round(2)` solution could be added if it fixed the delta calculation. Unfortunately, from what I can tell, it doesn’t necessarily produce the desired result. While it works for `74176.98f - 46336.89f`, it fails for `174176.98f - 146336.83f`, where the result would have to be rounded down to be correct.

It does look like something has to be changed here. Since, as described above, `calculateXGcd` determines the default _x_ step, removing the GCD search would constitute a regression. More specifically, the default scaling of charts would worsen. This isn’t optimal, but it does seem like less of an inconvenience than switching to `Int`s or `Long`s, which would make it impossible to use fractional _x_ values, forcing Vico users to do more data processing. If `calculateXGcd` is removed, it might be possible to add it back once we switch from `Float`s to `Double`s, which we plan on doing. I’ll discuss the matter with @Gowsky.

In the meantime, I suggest that you multiply your _x_ values by 10 (for one decimal place) or, if that doesn’t help, by 100 (for whole numbers). You can divide them during formatting to have the right values displayed along _x_-axes.

**Comment by littleant** [comment]
A dedicated precision check would be a solution I think. It would assert that there are no values with a precision lower than 0.01. Afterwards you can define the minimum GCD to be 0.01, regardless of what you detect in `calculateXGcd()`.

I agree, `round(2)` is not the solution here.

I think switching to `Double` would not solve the issue. It would just allow larger values until the same issue surfaces again. (You are just switching from 32bit to 64bit.)
Unless you keep the external API to only use `Float`s and immediately convert them to `Double`s for internal use (e.g. in `entryOf()`. This may work, I don't know.

If you don't want to switch to `Int` or `Long` in the external API, you could convert to `Long`s in the internal API, since you already restrict the precision. e.g. with this conversion logic:

- If x-value is of type `Float`, cast it to `Double`, multiply it by 100 and cast it to `Long`s for internal use.
- If x-value is of type `Double`, multiply by 100 and cast it to `Long`s. (This could be a problem with higher values)
- If x-value is of type `Int`, cast to `Long` and multiply by 100.
- If x-value is of type `Long`, multiply by 100. (This could also lead to problems, if values near `Long.MAX_VALUE` are being used.)

I have added this logic in the hopes that it prevents exceptions. (I'm not sure if `.toInt().toFloat()` actually does anything except hiding fractional digits?):
```
.setEntries(entries.map { entry ->
    FloatEntry(x = (entry.x * 100f).toInt().toFloat(), y = entry.y)
})
```

**Comment by patrickmichalik** [comment]
Thanks for the input, @littleant! Regarding switching to `Float`s to `Double`s, this problem would certainly reappear for some precision level, but what I had in mind is that `Double`s might be precise enough to give us a reasonably high precision level that consistently works. We’d still need a precision check. As can be seen here, with `Float`s, even two decimal places can be problematic, and a limit of one decimal place would be a bit too restrictive. About chaining `toInt` and `toFloat`, this doesn’t do anything beyond removing all decimals. A slightly more concise option is `floor(entry.x * 100f)`.

[Vico 2.0.0 Alpha 6](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.6) introduces an improvement that is helpful here: when you set a custom _x_ step, no GCD calculations are run. Thus, when the GCD algorithm fails due to precision issues, rather than transforming your data, you can simply explicitly specify the _x_ step. For your data, `getXStep = { 0.01f }` could be added, and everything should work as expected. Of course, it would be optimal for the GCD algorithm not to fail in the first place. We’ll continue to look into this.

**Comment by patrickmichalik** [comment]
[Vico 1.14.0 Beta 1](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0-beta.1) also includes the aforementioned improvement.
