### ISSUE TITLE
Exception when using Horizontal.fullWidth() with series with just 1 entry

### ISSUE THREAD

**Issue by rhult** [patrykandpatrick/vico#597]
### How to reproduce

Set up a chart with a full width horizontal layout, and provide a series with just one entry, for example:

```
@Preview(widthDp = 400)
@Composable
fun Chart(
) {
    val entries = listOf(
        Entry(x = 0, y = 1),
    )
    CartesianChartHost(
        chart = rememberCartesianChart(
            rememberLineCartesianLayer(),
            startAxis = rememberStartAxis(),
            bottomAxis = rememberBottomAxis(),
        ),
        model = CartesianChartModel(
            models = listOf(
                LineCartesianLayerModel.build {
                    series(
                        x = entries.map { it.x },
                        y = entries.map { it.y }
                    )
                },
            )
        ),
        horizontalLayout = HorizontalLayout.fullWidth(
            unscalableStartPadding = 10.dp,
            unscalableEndPadding = 10.dp,
        ),
    )
}
```

### Observed behavior

This results in an exception:

```
    java.lang.IllegalArgumentException: Cannot coerce value to an empty range: NaN..0.0.
    at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1470)
    at com.patrykandpatrick.vico.compose.chart.scroll.VicoScrollState.setValue(VicoScrollState.kt:75)
    at com.patrykandpatrick.vico.compose.chart.scroll.VicoScrollState.setMaxValue$compose_release(VicoScrollState.kt:85)
    at com.patrykandpatrick.vico.compose.chart.scroll.VicoScrollState.update$compose_release(VicoScrollState.kt:149)
    at com.patrykandpatrick.vico.compose.chart.CartesianChartHostKt$CartesianChartHostImpl$6.invoke(CartesianChartHost.kt:255)
    at com.patrykandpatrick.vico.compose.chart.CartesianChartHostKt$CartesianChartHostImpl$6.invoke(CartesianChartHost.kt:224)
    at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:116)
```

Adding one more entry, or removing the layout results in no crash.

### Expected behavior

No exception.

### Vico version(s)

Latest unstable version

### Android version(s)

14

### Additional information

This is with alpha 9. The same code worked with alpha 8 and earlier.

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ll look into this.

**Comment by patrickmichalik** [comment]
This crash occurs when there’s no scalable content. You can work around the issue by adding the following `Zoom` implementation to your project and setting `initialZoom` to `Zoom.max(Zoom.static(), ContentZoom)` for scrollable charts, and to `ContentZoom` for charts with scroll disabled. We’ll be releasing a hotfix soon.

```kt
val ContentZoom =
    Zoom { context, horizontalDimensions, bounds ->
        val scalableContentWidth = horizontalDimensions.getScalableContentWidth(context)
        if (scalableContentWidth == 0f) {
            1f
        } else {
            (bounds.width() - horizontalDimensions.unscalablePadding) / scalableContentWidth
        }
    }
```

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 10](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.10) fixes this. Cheers!

**Comment by rhult** [comment]
Thanks, alpha 10 works perfectly!

**Comment by patrickmichalik** [comment]
I’m glad to hear that! You’re welcome, and thanks again for letting us know about the bug.
