### ISSUE TITLE
IllegalStateException: Reading a state with latest compose alphas

### ISSUE THREAD

**Issue by brinsche** [patrykandpatrick/vico#625]
### How to reproduce

Thanks for this library, I really appreciate how good it looks by default and it seems nice to work with!

I'm encountering a crash after upgrading the material3 dependency to version 1.3.0-alpha03 which also pulls in the latest compose libraries with version 1.7.0-alpha05. In my app the crash seems to be 100% reliable.
I modified the sample to upgrade the dependencies and wrapped the chart in a LazyColum, the initially chosen chart seems to work still but using the arrows to switch between them produces the same error relatively reliably

Edit: It's obviously possible that this is a bug in the compose alphas and not vico, it's totally fine if you want to wait for at least a -beta release or something before looking into this.

```
LazyColumn {
    item {
        charts[arguments.getInt("chartID")](
            UISystem.entries[uiSystemID],
            Modifier.padding(horizontal = 16.dp),
        )
    }
}
```

### Observed behavior

`java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotKt.readError(Snapshot.kt:2033)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:2017)
                                                                                                    	at androidx.compose.runtime.SnapshotMutableStateImpl.getValue(SnapshotState.kt:135)
                                                                                                    	at com.patrykandpatrick.vico.compose.state.CartesianChartModelWrapperState.getValue(CartesianChartModelWrapper.kt:56)
                                                                                                    	at com.patrykandpatrick.vico.compose.model.ChartEntryModelExtensionsKt$collectAsState$1$startAnimation$1.invoke(ChartEntryModelExtensions.kt:69)
                                                                                                    	at com.patrykandpatrick.vico.compose.model.ChartEntryModelExtensionsKt$collectAsState$1$startAnimation$1.invoke(ChartEntryModelExtensions.kt:67)
                                                                                                    	at com.patrykandpatrick.vico.core.model.CartesianChartModelProducer$UpdateReceiver.handleUpdate(CartesianChartModelProducer.kt:230)
                                                                                                    	at com.patrykandpatrick.vico.core.model.CartesianChartModelProducer.registerForUpdates(CartesianChartModelProducer.kt:146)
                                                                                                    	at com.patrykandpatrick.vico.compose.model.ChartEntryModelExtensionsKt$collectAsState$1$1.invokeSuspend(ChartEntryModelExtensions.kt:108)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@114dbc9, androidx.compose.runtime.BroadcastFrameClock@74f02ce, StandaloneCoroutine{Cancelling}@8d325ef, Dispatchers.Default]`

### Expected behavior

No Crash

### Vico version(s)

Latest unstable version

### Android version(s)

Android 14

**Comment by patrickmichalik** [comment]
Hello! Thanks for the kind words and for the report. This would appear to be a Jetpack Compose bug—please see [here](https://issuetracker.google.com/issues/266062275).
