### ISSUE TITLE
Crash on changing dataset which contains negative values

### ISSUE THREAD

**Issue by dhruv2295** [patrykandpatrick/vico#666]
### How to reproduce

Run this code and it'll crash when dataset changes from a to b or b to a
```
@Composable
internal fun Chart() {
    val modelProducer = remember { CartesianChartModelProducer.build() }
    val a = List(50) { Random.nextFloat() * -20}
    val b = List(50) { Random.nextFloat() * 20}

    LaunchedEffect(Unit) {
        withContext(Dispatchers.Default) {
            while (isActive) {
                modelProducer.tryRunTransaction {
                    lineSeries { series(if (Random.nextBoolean()) a else b) }
                }
                delay(500)
            }
        }
    }
    CartesianChartHost(
        chart =
        rememberCartesianChart(
            rememberLineCartesianLayer(
                lines = listOf(rememberLineSpec(shader = DynamicShader.color(lineColor))),
            ),
            fadingEdges = rememberFadingEdges(),
        ),
        modelProducer = modelProducer,
        marker = rememberMarker(DefaultCartesianMarker.LabelPosition.AroundPoint),
        runInitialAnimation = false,
    )
}
```

### Observed behavior

App crashes when dataset goes from positive to negative and vice versa.

### Expected behavior

App doesn't crash. 

### Vico version(s)

Latest unstable version

### Android version(s)

14

### Additional information

```FATAL EXCEPTION: main
Process: com.demo.debug, PID: 19069
java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:1204)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1170)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1118)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1077)
at com.patrykandpatrick.vico.core.common.shader.TopBottomShader.createShader(TopBottomShader.kt:47)
at com.patrykandpatrick.vico.core.common.shader.CacheableDynamicShader.provideShader(CacheableDynamicShader.kt:36)
at com.patrykandpatrick.vico.core.cartesian.layer.LineCartesianLayer$LineSpec.drawBackgroundLine(LineCartesianLayer.kt:210)
at com.patrykandpatrick.vico.core.cartesian.layer.LineCartesianLayer.drawInternal(LineCartesianLayer.kt:323)
at com.patrykandpatrick.vico.core.cartesian.layer.LineCartesianLayer.drawInternal(LineCartesianLayer.kt:72)
at com.patrykandpatrick.vico.core.cartesian.layer.BaseCartesianLayer.draw(BaseCartesianLayer.kt:70)
at com.patrykandpatrick.vico.core.cartesian.CartesianChart$drawingModelAndLayerConsumer$1.invoke(CartesianChart.kt:66)
at com.patrykandpatrick.vico.core.cartesian.CartesianChart.forEachWithLayer(CartesianChart.kt:387)
at com.patrykandpatrick.vico.core.cartesian.CartesianChart.draw(CartesianChart.kt:194)
at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt$CartesianChartHostImpl$5.invoke(CartesianChartHost.kt:264)
at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt$CartesianChartHostImpl$5.invoke(CartesianChartHost.kt:214)
at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:116)
at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:364)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:926)
at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:926)
at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:926)
at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:383)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:382)
at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:382)
at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:380)
at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:335)
at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1236)
at android.view.View.draw(View.java:24193)
at android.view.View.updateDisplayListIfDirty(View.java:23056)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
at android.view.View.updateDisplayListIfDirty(View.java:23012)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
at android.view.View.updateDisplayListIfDirty(View.java:23012)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
at android.view.View.updateDisplayListIfDirty(View.java:23012)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4550)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4523)
at android.view.View.updateDisplayListIfDirty(View.java:23012)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:5234)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4900)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4049)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
at android.view.Choreographer.doFrame(Choreographer.java:938)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
2024-04-19 14:29:52.682 19069-19069 AndroidRuntime          com...ptcraftslab.finest.demo.debug  E  	at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)```

**Comment by patrickmichalik** [comment]
Hello! Thanks for the report. We’ve identified and resolved the issue. A hotfix is coming soon.

**Comment by patrickmichalik** [comment]
[Vico 2.0.0 Alpha 16](https://github.com/patrykandpatrick/vico/releases/tag/v2.0.0-alpha.16) resolves this. Cheers!

**Comment by dhruv2295** [comment]
That's awesome.  Thanks!!
