### ISSUE TITLE
Cannot Round NaN to Float

### ISSUE THREAD

**Issue by sean-brown-dev** [patrykandpatrick/vico#695]
### How to reproduce

I'm honestly not sure what specific scenario is causing this. I have a CartesianChartModel with 2 layers and it works totally fine for many data sets, but with one I am getting this error.

### Observed behavior

Navigating to page this error is thrown.

java.lang.IllegalArgumentException: Cannot round NaN value.
                                                                                                    	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.ShapeComponent.draw$lambda$3$drawShape(ShapeComponent.kt:165)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.ShapeComponent.access$draw$lambda$3$drawShape(ShapeComponent.kt:43)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.ShapeComponent$draw$1$1.invoke(ShapeComponent.kt:134)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.ShapeComponent$draw$1$1.invoke(ShapeComponent.kt:133)
                                                                                                    	at com.patrykandpatrick.vico.core.common.PaintKt.withOpacity(Paint.kt:33)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.ShapeComponent.draw(ShapeComponent.kt:133)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.LineComponent.drawHorizontal(LineComponent.kt:67)
                                                                                                    	at com.patrykandpatrick.vico.core.common.component.LineComponent.drawHorizontal$default(LineComponent.kt:58)
                                                                                                    	at com.patrykandpatrick.vico.core.cartesian.axis.VerticalAxis.drawBehindChart(VerticalAxis.kt:91)
                                                                                                    	at com.patrykandpatrick.vico.core.cartesian.axis.AxisManager.drawBehindChart(AxisManager.kt:150)
                                                                                                    	at com.patrykandpatrick.vico.core.cartesian.CartesianChart.draw(CartesianChart.kt:195)
                                                                                                    	at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt$CartesianChartHostImpl$5.invoke(CartesianChartHost.kt:268)
                                                                                                    	at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt$CartesianChartHostImpl$5.invoke(CartesianChartHost.kt:218)

### Expected behavior

Chart should draw.

### Vico version(s)

Latest unstable version

### Android version(s)

14

### Additional information

The bottom line is the one where yRange.minY and yRange.maxY are coming back as NaN. This results in an error further into the code when it's trying to draw the chart and it's using those values to sum something and then convert it to a float.

`public open class VerticalAxis<Position : AxisPosition.Vertical>(
    override val position: Position,
) : BaseAxis<Position>() {
    protected val areLabelsOutsideAtStartOrInsideAtEnd: Boolean
        get() =
            horizontalLabelPosition == Outside && position is AxisPosition.Vertical.Start ||
                horizontalLabelPosition == Inside && position is AxisPosition.Vertical.End

    protected val textHorizontalPosition: HorizontalPosition
        get() = if (areLabelsOutsideAtStartOrInsideAtEnd) HorizontalPosition.Start else HorizontalPosition.End

    /**
     * Determines for what _y_ values this [VerticalAxis] is to display labels, ticks, and guidelines.
     */
    public var itemPlacer: AxisItemPlacer.Vertical = AxisItemPlacer.Vertical.step()

    /**
     * Defines the horizontal position of each axis label relative to the axis line.
     */
    public var horizontalLabelPosition: HorizontalLabelPosition = Outside

    /**
     * Defines the vertical position of each axis label relative to its corresponding tick.
     */
    public var verticalLabelPosition: VerticalLabelPosition = Center

    override fun drawBehindChart(context: CartesianDrawContext): Unit =
        with(context) {
            var centerY: Float
            val yRange = chartValues.getYRange(position)`

**Comment by Gowsky** [comment]
Hello @sean-brown-dev,
>I'm honestly not sure what specific scenario is causing this. I have a CartesianChartModel with 2 layers and it works totally fine for many data sets, but with one I am getting this error.

Since there is a particular data set for which the crash occurs, could you use this data set to create a minimal reproducible example?

**Comment by sean-brown-dev** [comment]
This was my mistake, sorry! I had 3 charts on a page and it was actually not the multi-series one, but another one. I had an entry in it that was NaN because it was created via dividing by 0. I fixed that and the issue went away.

Thanks again for the quick reply and awesome library!

**Comment by Gowsky** [comment]
You're welcome!

**Comment by patrickmichalik** [comment]
I’ll be using “Close as not planned” because this turned out not to be a bug. No worries about the mistake. Thanks for the kind words!
